MSO/Controllers/ItemController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MSO.DataAccess;
using MSO.Models;
using System;
using System.Collections.Generic;

namespace MSO.Controllers
{
    public class ItemController : Controller
    {
        private string _MsoConnectionString;
        private readonly IConfiguration _config;

        public ItemController(IConfiguration config)
        {
            _config = config;
        }

        // GET: ItemController
        public ActionResult Index(Mso mso)
        {
            SQLHelper sQLHelper = new SQLHelper(_config["MsoSQLConnection"]);
            IList<Item> items = sQLHelper.GetMsoItems(mso.RequestNumber);

            return View(items);
        }

        // GET: ItemController/Details/5
        public ActionResult Details()
        {
            return View();
        }

        // GET: ItemController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ItemController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemController/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: ItemController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ItemController/Delete/5
        public ActionResult Delete()
        {
            return View();
        }

        // POST: ItemController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public ActionResult RemoveItem(int ItemCount, string RequestNumber)

        {
            SQLHelper sQLHelper = new SQLHelper(_config["MsoSQLConnection"]);
            sQLHelper.RemoveItemFromMso(ItemCount, RequestNumber);

            return RedirectPermanentPreserveMethod(Request.Headers["Referer"].ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddItem(int RequestNumber, string StockNumber, string Description, double Quantity, string Unit, double Gross, double Tare, double Net, string Value, List<string> item)
        {
            SQLHelper sQLHelper = new SQLHelper(_config["MsoSQLConnection"]);
            List<Item> items = new List<Item>(sQLHelper.GetMsoItems(RequestNumber));

            try
            {
                Mso mso = new Mso();
                int ItemCount = 0;

                if (items.Count == 0)
                {
                    ItemCount = 1;
                }
                else
                {
                    ItemCount = items.Count + 1;
                }

                sQLHelper.AddItemToMso(RequestNumber, StockNumber, Description, Quantity, Unit, Gross, Tare, Net, Value, ItemCount);

                if (Request.Headers["Referer"].ToString().Contains("edit"))
                {
                    return RedirectToAction("Edit", "Mso", new { id = RequestNumber });
                }
                else
                {
                    return RedirectToAction("Create", "Mso", new { id = RequestNumber });
                }
            }
            catch
            {
                return View("Edit", "Mso");
            }
        }
    }
}

MSO/Views/Template/List.cshtml
@model X.PagedList.IPagedList<MSO.Models.Template>
@using X.PagedList.Mvc.Core;

@{ ViewData["Title"] = "Details"; }

<script type="text/javascript">
    function ShowThis() {
        $('#gateTran').show();
        $('#creditTran').hide();
        $('#cashTran').hide();
        $('#returnTran').hide();
    }

    function Selected(bool) {
        var setbool = bool.value;

        if (setbool == 4) {
            $('#Return').click();

        }
        else if (setbool == 3) {
            $('#Return').click();
        }
        else if (setbool == 2) {
            $('#Return').click();
        }
        else if (setbool == 1) {
            $('#Return').click();
        }
    }
    function ShowOption(radio) {
        var setdRad = radio.value;

        if (setdRad == 4) {
            $('#gateTran').show();
            $('#cashTran').hide();
            $('#creditTran').hide();
            $('#returnTran').hide();
        }
        else if (setdRad == 3) {
            $('#returnTran').show();
            $('#gateTran').hide();
            $('#creditTran').hide();
            $('#cashTran').hide();
        }
        else if (setdRad == 2) {
            $('#creditTran').show();
            $('#cashTran').hide();
            $('#gateTran').hide();
            $('#returnTran').hide();
        }
        else if (setdRad == 1) {
            $('#cashTran').show();
            $('#gateTran').hide();
            $('#creditTran').hide();
            $('#returnTran').hide();
        }
    }
    function UpdateAddress(string) {
        $('#ShipName').value = Name[0];
        $('#ShipAddress').value = Address[1];
        $('#ShipCity').value = City[2];
        $('#ShipState').value = State[3];
        $('#ShipZip').value = Zip[4];
    }
    function HideAll() {
        $('#cashTran').hide();
        $('#creditTran').hide();
        $('#returnTran').hide();
    }
</script>

<style>
    .ul.pagination {
        display: inline-block;
        padding: 0;
        margin: 0;
    }

    ul.pagination li {
        display: inline;
    }

        ul.pagination li a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
        }

            ul.pagination li a.active {
                background-color: #4CAF50;
                color: white;
            }

            ul.pagination li a:hover:not(.active) {
                background-color: #ddd;
            }
</style>
<h1>Template</h1>

@if (Model.FirstOrDefault().RoleId != 0)
{
    <p>
        <a asp-action="TemplateCreate">Create A New Template</a>
    </p>
}

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Name")
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

                <td>
                    @if (Convert.ToInt32(item.RoleId) == 1 || Convert.ToInt32(item.RoleId) == 2)
                    {
                        @Html.ActionLink("Edit | ", "Edit", new { id = item.Id })
                        @Html.ActionLink("Details | ", "Details", new { id = item.Id, name = item.Name })
                        @Html.ActionLink("Delete | ", "Delete", new { id = item.Id })

}

                    @if (Convert.ToInt32(item.RoleId) == 0)
                    {
                        @Html.ActionLink("Details | ", "Details", new { id = item.Id, name = item.Name })

}
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="container" style="margin-left: 20px">
    <p></p>
    <p></p>
    <div class="pagination" style="margin-left: 200px">
        @Html.PagedListPager((X.PagedList.IPagedList)Model, page => Url.Action("List", "Template", new { page }))
    </div>
</div>

MSO/Views/Template/_CreateTemplate.cshtml
@model IList<MSO.Models.Template>

@{

}
<script type="text/javascript">

    $('#gateTran').show();
    $('#creditTran').hide();
    $('#cashTran').hide();
    $('#returnTran').hide();

    function UpdateNet() {
        document.getElementById("Net").value = document.getElementById("Gross").value - document.getElementById("Tare").value;
    }
    function MaintainData() {

        var shipTo1 = document.getElementById("Attention").value;
        var shipTo2 = document.getElementById("ShipName").value;
        var shipTo3 = document.getElementById("ShipAddress").value;
        var shipTo4 = document.getElementById("ShipCity").value;
        var shipTo5 = document.getElementById("ShipState").value;
        var shipTo6 = document.getElementById("Zip").value;

        var testdata = (shipTo1 + ", " + shipTo2 + ", " + shipTo3 + ", " + shipTo4 + ", " + shipTo5 + ", " + shipTo6)
        alert(testdata);
    }
    function ShowOption(radio) {
        var setdRad = radio.value;

        if (setdRad == 4) {
            $('#gateTran').show();
            $('#cashTran').hide();
            $('#creditTran').hide();
            $('#returnTran').hide();
        }
        else if (setdRad == 3) {
            $('#returnTran').show();
            $('#gateTran').hide();
            $('#creditTran').hide();
            $('#cashTran').hide();
        }
        else if (setdRad == 2) {
            $('#creditTran').show();
            $('#cashTran').hide();
            $('#gateTran').hide();
            $('#returnTran').hide();
        }
        else if (setdRad == 1) {
            $('#cashTran').show();
            $('#gateTran').hide();
            $('#creditTran').hide();
            $('#returnTran').hide();
        }
    }
    function ShowFOB(radio) {
        var setdRad = radio.value;

        if (setdRad == 1) {
            $('#OurPlant').show();
            $('#Destination').hide();
            $('#OtherSpcify').hide();
        }
        else if (setdRad == 2) {
            $('#Destination').show();
            $('#OurPlant').hide();
            $('#OtherSpecify').hide();
        }
        else if (setdRad == 3) {
            $('#OtherSpecify').show();
            $('#OurPlant').hide();
            $('#Destination').hide();
        }
    }
    function Freight(radio) {
        var setdRad = radio.value;

        alert(setdRad);

        if (setdRad == 3) {
            document.getElementById('Invoice').checked = false;
            document.getElementById('Allow').checked = false;

        }
        else if (setdRad == 2) {
            document.getElementById('Invoice').checked = false;
            document.getElementById('Collect').checked = false;
        }
        else if (setdRad == 1) {
            document.getElementById('Allow').checked = false;
            document.getElementById('Collect').checked = false;
        }
    }

    function PopulateTemplate(val) {
        var xmlhttp = new XMLHttpRequest();
        alert("partial");
        if (xmlhttp && val != "0") {
            xmlhttp.open("GET", "/TemplateClass/GetTemplate?Name=" + val,
                false);
            xmlhttp.setRequestHeader('Content-Type',
                'application/x-www-form-urlencoded');

            xmlhttp.send(null);
            alert(xmlhttp.responseText);

            var tempAndItems = xmlhttp.responseText.split("##!##");
            var values = tempAndItems[0].split(",");

            //Ship To
            var shipTo1 = values[45].replace(/"/g, '').replace("vendor:{name:", '');
            var shipTo2 = values[46].replace(/"/g, '').replace("address:", '');
            var shipTo3 = values[47].replace(/"/g, '').replace("city:", '');
            var shipTo4 = values[48].replace(/"/g, '').replace("state:", '');
            var shipTo5 = values[49].replace(/"/g, '').replace("zip:", '');
            var freight = values[44].replace(/"/g, '').replace("freight:", '');

            document.getElementById("ShipName").value = shipTo1;
            document.getElementById("ShipAddress").value = shipTo2;
            document.getElementById("ShipCity").value = shipTo3;
            document.getElementById("ShipState").value = shipTo4;
            document.getElementById("Zip").value = shipTo5;

            // Requested By
            var requestedby = values[4].replace(/"/g, '').replace("requestedByName:", '');
            requestedby = (requestedby != null) ? requestedby : "N/A";
            document.getElementById("appReqName").value = requestedby;

            // Remarks
            var remarks = values[20].replace(/"/g, '').replace("remarks:", '');
            remarks = (remarks.toString != null) ? remarks : "N/A";
            document.getElementById("Remarks").value = remarks;

            //Shipping Instructions
            var instructions = values[21].replace(/"/g, '').replace("shippingInstructions:", '');
            instructions = (instructions != null) ? instructions : "N/A";
            document.getElementById("Instruction").value = instructions;

            //Buyer
            var buyer = values[23].replace(/"/g, '').replace("buyer:", '');
            buyer = (buyer != null) ? buyer : "N/A";
            document.getElementById("buyerSelect").value = buyer;

            //Completed By
            var completedby = values[22].replace(/"/g, '').replace("completedBy:", '');
            completedby = (completedby != null) ? completedby : "N/A";
            document.getElementById("CompletedBy").value = completedby;

            // Ship Via
            var shipvia = values[51].replace(/"/g, '').replace("shipVia:", '');
            shipvia = (shipvia != null) ? shipvia : "N/A";
            document.getElementById("ShipVia").value = shipvia;

            // Requested By Department
            var requestedbydepartment = values[35].replace(/"/g, '').replace("requestedByDepartment:", '');
            requestedbydepartment = (requestedbydepartment != null) ? requestedbydepartment : "N/A";
            document.getElementById("appReqDept").value = requestedbydepartment;

            //Sold To
            var soldTo1 = values[36].replace(/"/g, '').replace("soldTo1:", '');
            var soldTo2 = values[37].replace(/"/g, '').replace("soldTo2:", '');
            var soldTo3 = values[38].replace(/"/g, '').replace("soldTo3:", '');
            var soldTo4 = values[39].replace(/"/g, '').replace("soldTo4:", '');

            document.getElementById("SoldName").value = soldTo1;
            document.getElementById("SoldAddress").value = soldTo1;
            document.getElementById("SoldCity").value = soldTo2;
            document.getElementById("SoldState").value = soldTo3;
            document.getElementById("SoldZip").value = soldTo4;

            // Freight

            if (freight == 1) {
                document.getElementById("Invoice").value = freight;
                Freight(this);
            }
            else if (freight == 2) {
                document.getElementById("Allow").value = freight;
                Freight(this);
            }
            else if (freight == 3) {
                document.getElementById("Collect").value = freight;
                Freight(this);
            }

            // Transaction Type
            var transaction = values[5].replace(/"/g, '').replace("transactionType:", '');
            if (transaction == 1) {
                document.getElementById("cash").value = transaction;
                ShowOptions(transaction);
            }
            else if (transaction == 2) {
                document.getElementById("credit").value = transaction;
                ShowOptions(transaction);
            }
            else if (transaction == 3) {
                document.getElementById("return").value = transaction;
                ShowOptions(transaction);
            }
            else if (transaction == 4) {
                document.getElementById("gate").value = transaction;
                ShowOptions(transaction);
            }

            // FOB
            var fob = value[45].replace(/"/g, '').replace("fob:", '');
            alert(fob);

            if (fob == 1) {
                document.getElementById("OurPlant").checked = true;
                ShowFOB(fob);
            }
            else if (fob == 2) {
                document.getElementById("Destination").checked = true;
                ShowFOB(fob);
            }
            else if (fob == 3) {
                document.getElementById("OtherSpecify").checked = true;
                ShowFOB(fob);
            }

        }
    }
    function getXMLObject() // XML OBJECT
    {
        var xmlHttp = false;
        try {
            xmlHttp = new ActiveXObject("Msxml2.XMLHTTP"); // For Old Microsoft
            // Browsers
        } catch (e) {
            try {
                xmlHttp = new ActiveXObject("Microsoft.XMLHTTP"); // For Microsoft
                // IE 6.0+
            } catch (e2) {
                xmlHttp = false; // No Browser accepts the XMLHTTP Object then
                // false
            }
        }
        if (!xmlHttp && typeof XMLHttpRequest != 'undefined') {
            xmlHttp = new XMLHttpRequest(); // For Mozilla, Opera Browsers
        }
        return xmlHttp; // Mandatory Statement returning the ajax object created
    }
    function toCelsius(fahrenheit) {
        return (5 / 9) * (fahrenheit - 32);
    }
    function HideAll() {
        $('#cashTran').hide();
        $('#creditTran').hide();
        $('#returnTran').hide();
    }
</script>
<body onload="HideAll()" onreset="MaintainData()">

    <div class="card-body">
        <label><b>Ship To Template</b></label>
        <select id="Templates" name="Templates" onchange="PopulateTemplate(document.getElementById('Templates').value)">
            @if (Model.Count != 0)
            {
                <option>Please select a template</option>

                int templatecount = 0;
                @foreach (var template in Model)
                {
                    <option value=@Model.ElementAtOrDefault(templatecount).Shipment.Name>@Model.ElementAtOrDefault(templatecount).Shipment.Name</option>
                    templatecount++;
                }
            }
        </select>
    </div>
</body>

MSO/Views/Template/_TemplateItems.cshtml
@model MSO.Models.Template

@{

}
<script type="text/javascript">
    function UpdateNet() {
        document.getElementById("Net").value = document.getElementById("Gross").value - document.getElementById("Tare").value;
    }
    function AddItem(val) {
        alert(val);
    }
</script>
<div class="card-body">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayName("Items")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Items.Count != 0)
            {
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gross)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Net)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Quantity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Unit)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Value)
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "RemoveItem", "Item", new { ItemCount = item.ItemCount, RequestNumber = item.RequestNumber })
                        </td>
                    </tr>
                }
            }
            else
            {
                <p> There are no items.</p>
            }
        </tbody>
    </table>
</div>
<div class="justify-content-md-center">
    <form asp-controller="TemplateItem" asp-action="AddItem" id="Items" class="card-header">
        <div class="card-body">
            <div class="card bg-light mb-3">
                <div class="card-header">Add Items</div>
                <div class="card-body">

                    <input hidden id="RequestNumber" name="RequestNumber" asp-for="@Model.RequestNumber" type="text" />
                    <table class="card-deck" id="submissionTable">
                        <tbody>

                            <tr>
                                <td>
                                    <div class="card-columns">
                                        @Html.Label("Stock #")
                                        <input id="StockNumber" name="StockNumber" type="text" />
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Description")
                                    <input id="Description" name="Description" type="text" required="required" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Quantity")
                                    <input id="Quantity" name="Quantity" type="text" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Unit")
                                    @Html.DropDownList("Unit", new List<SelectListItem>
                                        {
                                        new SelectListItem() {Text = "EA", Value="EA"},
                                        new SelectListItem() {Text = "SKID", Value="SKID"},
                                        new SelectListItem() {Text = "LOAD", Value="LOAD"},
                                        new SelectListItem() {Text = "SET", Value="SET"},

                                        })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Gross")
                                    <input id="Gross" name="Gross" type="text" required="required" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Tare")
                                    <input id="Tare" name="Tare" onchange="UpdateNet()" type="text" required="required" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Net")
                                    <input type="text" id="Net" name="Net" required="required" />
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.Label("Value")
                                    <input name="Value" id="Value" type="text" required="required" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <hr />
                </div>
            </div>
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </form>
</div>