MSO/Models/Waste.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSO.Models
{
    public class Waste
    {
        public int RequestNumber { get; set; }
        public string CreationDate { get; set; }
        public string Hauler { get; set; }
        public string Description { get; set; }
        public int Weight { get; set; }
    }
}

MSO/Controllers/WasteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using System.Linq;
using System.Threading.Tasks;
using MSO.Models;
using PagedList;
using MSO.DataAccess;
using MSO.Tools;

namespace MSO.Controllers
{
    public class WasteController : Controller
    {
        private readonly IConfiguration _config;
        private string _MsoSQLConnection;

        public WasteController(IConfiguration config)
        {
            _config = config;
        }

        public ActionResult Index(string StartDate, string EndDate, int? page, string sortOrder)
        {
            SQLHelper sQLHelper = new SQLHelper(_config["MsoSQLConnection"]);
            Utilities utilities = new Utilities(_config["MsoSQLConnection"]);
            IList<Waste> waste = new List<Waste>();

            if (page == null)
            {
                return View();
            }
            else
            {
                int pageSize = 50;
                int pageNumber = (page ?? 1);
                waste = sQLHelper.GetWastes();

                pageNumber = (pageNumber != 0) ? pageNumber : 1;
                return View(waste.ToPagedList(pageNumber, pageSize));
            }
        }

        public ActionResult Details(string id)
        {
            SQLHelper sQLHelper = new SQLHelper(_config["MsoSQLConnection"]);
            Utilities utilities = new Utilities(_config["MsoSQLConnection"]);
            Waste waste = new Waste();
            waste = sQLHelper.GetWaste(id);
            return View(waste);
        }

        public ActionResult Waste(string StartDate, string EndDate, int? page, string sortOrder)
        {
            Files files = new Files(_config["MsoSQLConnection"]);
            IList<Waste> waste = new List<Waste>();

            if (StartDate == null && EndDate == null)
            {
                return View();
            }
            else
            {
                int pageSize = 50;
                int pageNumber = (page ?? 1);
                waste = files.BuildWasteFile(StartDate, EndDate);

                pageNumber = (pageNumber != 0) ? pageNumber : 1;
                return View(waste.ToPagedList(pageNumber, pageSize));
            }
        }

        //public void DownloadReport(string StartDate, string EndDate, string user)
        //{
        //    Utilities utilities = new Utilities(_config);
        //    IList<Waste> waste = new List<Waste>();
        //    user = User.Identity.Name;
        //    waste = utilities.DownloadWasteExcel(StartDate, EndDate, user);
        //    return;
        //}
    }
}

MSO/Views/Waste/Details.cshtml
@model MSO.Models.Waste
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="card-header">
    <fieldset>
        <legend>Waste MSO</legend>
        <div class="inFieldset">
            <table>
                <tbody>
                    <tr>
                        <td>Req. No</td>
                        <td><input type="text" id="RequestNumber" name="RequestNumber" asp-for="RequestNumber" tabindex="17" readonly="readonly"></td>
                    </tr>
                    <tr>
                        <td>Hauler</td>
                        <td><input type="text" id="Hauler" name="Hauler" asp-for="Hauler" tabindex="18" style="max-width: 70rem; align-content:baseline" value="" readonly="readonly"></td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        <td><input type="text" id="Description" name="Description" asp-for="Description" tabindex="19"></td>
                    </tr>
                    <tr>
                        <td>Weight</td>
                        <td><input type="text" id="Weight" name="Weight" asp-for="Weight" tabindex="20"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </fieldset>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

MSO/Views/Waste/Index.cshtml
@model PagedList.IPagedList<MSO.Models.Waste>
@using PagedList.Mvc;
@{ ViewData["Title"] = "Index"; }

<h1>Waste</h1>
<script type="text/javascript">
    function DownloadReport(val) {
        var xmlhttp = new XMLHttpRequest();
        var values = val.split(" ");
        xmlhttp.open("POST", "/waste/DownloadReport?StartDate=" + values[0] + "EndDate=" + values[1],
            false);
        xmlhttp.setRequestHeader('Content-Type',
            'application/x-www-form-urlencoded');

        xmlhttp.send(null);
        alert("File (wastemso.csv) downloaded to your downloads folder.");
    }
    function getXMLObject() // XML OBJECT
    {
        var xmlHttp = false;
        try {
            xmlHttp = new ActiveXObject("Msxml2.XMLHTTP"); // For Old Microsoft
            // Browsers
        } catch (e) {
            try {
                xmlHttp = new ActiveXObject("Microsoft.XMLHTTP"); // For Microsoft
                // IE 6.0+
            } catch (e2) {
                xmlHttp = false; // No Browser accepts the XMLHTTP Object then
                // false
            }
        }
        if (!xmlHttp && typeof XMLHttpRequest != 'undefined') {
            xmlHttp = new XMLHttpRequest(); // For Mozilla, Opera Browsers
        }
        return xmlHttp; // Mandatory Statement returning the ajax object created
    }
</script>
<form asp-controller="Waste" asp-action="waste" method="post">

    @{
        if (Model == null)
        {
            DateTime dt = DateTime.Now;
            <span>@Html.Label("From Date")</span>
            @Html.Label("To Date")
            <br />
            @Html.TextBox("startDate", String.Format("{0:d}", dt.ToShortDateString()), new { @class = "datefield", type = "date", required = "required" })
            <span></span>
            @Html.TextBox("endDate", String.Format("{0:d}", dt.ToShortDateString()), new { @class = "datefield", type = "date", required = "required" })

            <br />
            <br />

            <input type="submit" name="Waste" value="View">
            <input type="button" name="Download" value="Download" onclick="DownloadReport(document.getElementById('startDate').value + '&nbsp;' + document.getElementById('endDate').value)" />
        }
        else
        {
            <input type="button" name="Download" value="Download" onclick="DownloadReport(document.getElementById('startDate').value+ '&nbsp;' + document.getElementById('endDate').value)" />
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.FirstOrDefault().RequestNumber)
                        </th>

                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RequestNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreationDate)
                            </td>

                            <td>

                                @Html.ActionLink("Edit | ", "Edit", new { id = item.RequestNumber })
                                @Html.ActionLink("Details | ", "Details", new { id = item.RequestNumber })
                                @Html.ActionLink("Delete", "Delete", new { id = item.RequestNumber })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

            <ul class="pagination pagination-sm">
                @for (int i = 1; i <= Model.PageCount; i++)
                {
                    <li class="@(i == Model.PageNumber ? "page-item active" : "page-item")">
                        <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
                    </li>
                }
            </ul>

        }

    }
</form>

MSO/Views/Waste/Waste.cshtml
@model PagedList.IPagedList<MSO.Models.Waste>
@using PagedList.Mvc;

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Request Number")
            </th>

            <th>
                 @Html.DisplayName("Date")
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RequestNumber)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>

                <td>

                    @Html.ActionLink("Details", "Details", new { id = item.RequestNumber })
                </td>
            </tr>
        }
    </tbody>
</table>

<ul class="pagination pagination-sm">
    @for (int i = 1; i <= Model.PageCount; i++)
    {
        <li class="@(i == Model.PageNumber ? "page-item active" : "page-item")">
            <a class="page-link" href="@Url.Action("Index", new { page = i })">@i</a>
        </li>
    }
</ul>